INSERT  INTO
	xzkx_article_record
      ( 
      id                            
      ,userid                         
      ,name                           
      ,department                     
      ,articleid                      
      ,accountid                      
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,update_name                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :xzkxArticleRecord.id                            
      ,:xzkxArticleRecord.userid                        
      ,:xzkxArticleRecord.name                          
      ,:xzkxArticleRecord.department                    
      ,:xzkxArticleRecord.articleid                     
      ,:xzkxArticleRecord.accountid                     
      ,:xzkxArticleRecord.createName                    
      ,:xzkxArticleRecord.createBy                      
      ,:xzkxArticleRecord.createDate                    
      ,:xzkxArticleRecord.updateName                    
      ,:xzkxArticleRecord.updateBy                      
      ,:xzkxArticleRecord.updateDate                    
      )