INSERT  INTO
	xzkx_menu
      ( 
      ID                            
      ,CREATE_BY                      
      ,CREATE_DATE                    
      ,CREATE_NAME                    
      ,IMAGE_HREF                     
      ,IMAGE_NAME                     
      ,NAME  
      ,ALIAS
      ,TYPE                           
      ,PARENT_CODE                    
      ,HREF                           
      ) 
values
      (
      :xzkxMenu.id                            
      ,:xzkxMenu.createBy                      
      ,:xzkxMenu.createDate                    
      ,:xzkxMenu.createName                    
      ,:xzkxMenu.imageHref                     
      ,:xzkxMenu.imageName                     
      ,:xzkxMenu.name                          
      ,:xzkxMenu.alias                          
      ,:xzkxMenu.type                          
      ,:xzkxMenu.parentCode                    
      ,:xzkxMenu.href                          
      )