INSERT  INTO
	xzkx_site
      ( 
      ID                            
      ,COMPANY_TEL     
      ,CREATE_DATE                    
      ,CREATE_NAME                    
      ,SITE_LOGO                      
      ,SITE_NAME                      
      ,SITE_TEMPLATE_STYLE            
      ,UPDATE_DATE                    
      ,UPDATE_NAME                    
      ) 
values
      (
      :xzkxSite.id                            
      ,:xzkxSite.companyTel                        
      ,:xzkxSite.createDate                    
      ,:xzkxSite.createName                    
      ,:xzkxSite.siteLogo                      
      ,:xzkxSite.siteName                      
      ,:xzkxSite.siteTemplateStyle             
      ,:xzkxSite.updateDate                    
      ,:xzkxSite.updateName                    
      )