INSERT  INTO
	xzkx_article
      ( 
      id                            
      ,title                          
      ,image_href                     
      ,summary                        
      ,content                        
      ,column_id                      
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,publish                        
      ,PUBLISH_DATE                   
      ,AUTHOR
      ,department
      ,LABEL                          
      ,AGENT_ID
      ,ext_url
      ) 
values
      (
      :xzkxArticle.id                            
      ,:xzkxArticle.title                         
      ,:xzkxArticle.imageHref                     
      ,:xzkxArticle.summary                       
      ,:xzkxArticle.content                       
      ,:xzkxArticle.columnId                      
      ,:xzkxArticle.createName                    
      ,:xzkxArticle.createBy                      
      ,:xzkxArticle.createDate                    
      ,:xzkxArticle.publish                       
      ,:xzkxArticle.publishDate                   
      ,:xzkxArticle.author                        
      ,:xzkxArticle.department                     
      ,:xzkxArticle.label                         
      ,:xzkxArticle.agentId
      ,:xzkxArticle.extUrl
      )